#!/usr/bin/perl

$is_commit = 0;
foreach (@ARGV) {
  if ($_ eq 'ci' || $_ eq 'commit') {
    $is_commit = 1;
    last;
  }
}
if ($is_commit == 0) {
  print "This is not a CVS commit!\n";
  exit;
}

system 'cp Makefile Makefile.bak';
open MAKEFILE_BAK, "<Makefile.bak";
open MAKEFILE, ">Makefile";
while (<MAKEFILE_BAK>) {
  if (/PACKAGE_VERSION\ =\ ([0-9]+)\.([0-9]+)\.(-?[0-9]+)/) {
    $old_version = "$1.$2.$3";
    $new_version = "$1.$2." . ($3 + 1);
    print MAKEFILE "PACKAGE_VERSION = $new_version\n";
    print "Updating version to $new_version\n";
  }
  else {
    print MAKEFILE $_;
  }
}
close MAKEFILE_BAK;
close MAKEFILE;


if (system('cvs', @ARGV) != 0) {
  system 'cp Makefile.bak Makefile';
}
else {
  if ((system 'make dist > /dev/null && echo put dino-' . $new_version .
       '.tar.bz2 | ' .
       'sftp larsl@shell1.sf.net:/home/groups/d/di/dinoseq/htdocs/snapshot/' .
       ' > /dev/null') != 0) {
    printf "Could not upload snapshot!\n";
  }
  else {
    if ((system 'ssh larsl@shell1.sourceforge.net "echo ' . $new_version .
	 ' > /home/groups/d/di/dinoseq/htdocs/development_version"') != 0) {
      printf "Could not update the development version on the webpage!\n";
    }
    else {
      if ((system 'ssh larsl@shell1.sf.net rm -f ' .
    	   '/home/groups/d/di/dinoseq/htdocs/snapshot/dino-' . $old_version .
    	   '.tar.bz2') != 0) {
    	printf "Could not remove old snapshot!\n";
      }
    }
  }
}


