#!/bin/bash


# Prints the last annotated tag beginning with Version_ , the number
# of commits since then and the abbreviated object name of the current commit
git describe --match 'Version_*'            |

# Strips off the Version_ prefix
    sed 's/Version_//'                      |

# Changes - to spaces, making the tag version, the commit number and
# the object name separate words
    sed 's/-/ /g'                           |

# Strips off the object name
    awk '{ print $1 " " $2}'                |

# Changes the last .number in the tag version to a separate word
    sed -r 's/\.([0-9]+) / \1 /'            |

# Prints the tag version with the commit number added to the last .number
    awk '{ print $1 "." $2+$3 }'            |

# Strips off the linebreak
    xargs echo -n


# Add .EDITED to the version number if any files have been modified since
# the last commit
if test $(git ls-files --modified | wc -l) -gt 0 ; then
    echo .EDITED
else
    echo
fi